#' Remove all cohorts from one or several PFTs
#'
#' @export
remove_pft_from_history_file <- function(file,file_mod,PFT2remove = c()){

hfile <- hdf5r::H5File$new(file)
 
PFTs <- readDataSet(hfile[["PFT"]])
which2keep <- which(!(PFTs %in% PFT2remove))

Ncohort <- length(which2keep)
Npatch <-  readDataSet(hfile[["NPATCHES_GLOBAL"]])
PACO_N <- readDataSet(hfile[["PACO_N"]])
PAN <- rep(1:Npatch,PACO_N)[which2keep]
PAN_count <- as.vector(table(PAN))

variables <- c( 
  "AGB_CO","A_CLOSED", "A_CO2", "A_LIGHT",  "A_OPEN", "A_RUBP","BALIVE","BA_CO", "BDEAD", "BLEAF",
   "BROOT", "BSAPWOODA","BSAPWOODB","BSEEDS_CO","BSTORAGE",
   "CBR_BAR",
   "CENSUS_STATUS","CROWN_AREA_CO","DAGB_DT",  "DBA_DT","DBH",  
   "DDBH_DT",  "DELTA_DBH","DLNAGB_DT","DLNBA_DT", "DLNDBH_DT",   
   "ELONGF","FIRST_CENSUS", "FSN",   "FSW",   "FS_OPEN", 
   "GPP",   "GSW_CLOSED",   "GSW_OPEN", "HIGH_LEAF_PSI_DAYS","HITE", 
   "KRDEPTH",  "LAI_CO","LAST_GJ",  "LAST_GV",  "LEAF_DROP",   
   "LEAF_ENERGY",  "LEAF_FLIQ","LEAF_GBH", "LEAF_GBW", "LEAF_GROWTH_RESP",  
   "LEAF_GSW", "LEAF_HCAP","LEAF_MAINTENANCE","LEAF_PSI", "LEAF_RESPIRATION",  
   "LEAF_RWC", "LEAF_STORAGE_RESP","LEAF_TEMP","LEAF_TEMP_PV", "LEAF_VPDEF",  
   "LEAF_WATER",   "LEAF_WATER_INT","LIGHT_LEVEL",  "LIGHT_LEVEL_BEAM","LIGHT_LEVEL_DIFF",
   "LINT_CO2_CLOSED","LINT_CO2_OPEN","LINT_SHV", "LLSPAN","LOW_LEAF_PSI_DAYS", 
   "LSFC_CO2_CLOSED","LSFC_CO2_OPEN","LSFC_SHV_CLOSED","LSFC_SHV_OPEN","MONTHLY_DLNNDT",    
   "MONTHLY_DNDT", "NEW_RECRUIT_FLAG","NPLANT","PAR_L",
   "PAR_LEVEL_BEAM","PAR_LEVEL_DIFFD","PAR_LEVEL_DIFFU","PAR_L_BEAM", "PAR_L_DIFFUSE"  ,   
   "PAW_AVG",  "PFT",   "PHENOLOGY_STATUS","PSI_CLOSED",   "PSI_OPEN",
    "RECRUIT_DBH",  "RLONG_L",  "RLONG_W",  "ROOT_GROWTH_RESP",  
   "ROOT_MAINTENANCE","ROOT_RESPIRATION","ROOT_STORAGE_RESP","RSHORT_L", "RSHORT_L_BEAM",     
   "RSHORT_L_DIFFUSE","RSHORT_W", "RSHORT_W_BEAM","RSHORT_W_DIFFUSE","SAPA_GROWTH_RESP",  
   "SAPA_STORAGE_RESP","SAPB_GROWTH_RESP","SAPB_STORAGE_RESP","SLA",   "TODAY_GPP",   
   "TODAY_GPP_LIGHTMAX","TODAY_GPP_MLMAX","TODAY_GPP_MOISTMAX","TODAY_GPP_POT","TODAY_LEAF_RESP",   
   "TODAY_NPPCROOT","TODAY_NPPDAILY","TODAY_NPPFROOT","TODAY_NPPLEAF","TODAY_NPPSAPWOOD",  
   "TODAY_NPPSEEDS","TODAY_NPPWOOD","TODAY_ROOT_RESP","TURNOVER_AMP", "VEG_WIND",
   "VM0",   "VM_BAR","WAI_CO","WATER_SUPPLY", "WFLUX_GW",
   "WFLUX_WL", "WOOD_ENERGY",  "WOOD_FLIQ","WOOD_GBH",
   "WOOD_GBW", "WOOD_HCAP","WOOD_PSI", "WOOD_RWC", "WOOD_TEMP",   
   "WOOD_TEMP_PV", "WOOD_WATER","WOOD_WATER_INT")

variables2 <- c("CB","CB_LIGHTMAX","CB_MLMAX","CB_MOISTMAX","MORT_RATE_CO","RAD_PROFILE_CO","WFLUX_GW_LAYER")

# No cohort dimensions
variables3 <- c("AGE","AGRI_STOCKING_DENSITY","AGRI_STOCKING_PFT","ALBEDO","ALBEDO_NIR","ALBEDO_PAR","AREA","AREA_SI","ASPECT","AVG_DAILY_TEMP","AVG_MONTHLY_GNDWATER","AVG_MONTHLY_WATERDEF","A_DECOMP","BASEFLOW","BASEFLOW_SI","CAN_CO2","CAN_DEPTH","CAN_PRSS","CAN_RHOS","CAN_SHV","CAN_TEMP","CAN_TEMP_PV","CAN_THEIV","CAN_THETA","CAN_VPDEF","CBUDGET_INITIALSTORAGE","CBUDGET_NEP","CCWD_FLUX","CDEAD_GROW","CLEAF_GROW","CLEAF_LITTER_FLUX","CO2BUDGET_DENSEFFECT","CO2BUDGET_GPP","CO2BUDGET_INITIALSTORAGE","CO2BUDGET_LOSS2ATM","CO2BUDGET_PLRESP","CO2BUDGET_RESIDUAL","CO2BUDGET_RH","COSAOI","COSZ","CPWP","CROOT_GROW","CROOT_LITTER_FLUX","CSTAR","CSTORE_GROW","CWD_C_PY","CWD_N_PY","CWD_RH","DAYLIGHT","DIST_TYPE","EBUDGET_DENSEFFECT","EBUDGET_INITIALSTORAGE","EBUDGET_LOSS2ATM","EBUDGET_LOSS2DRAINAGE","EBUDGET_LOSS2RUNOFF","EBUDGET_NETRAD","EBUDGET_PRECIPGAIN","EBUDGET_PRSSEFFECT","EBUDGET_RESIDUAL","ELEVATION","FAST_SOIL_C","FAST_SOIL_C_PY","FAST_SOIL_N","FAST_SOIL_N_PY","FF_NHGT","FSC_IN","FSN_IN","F_DECOMP","GGBARE","GGNET","GGSOIL","GGVEG","GROUND_FLIQ","GROUND_SHV","GROUND_SSH","GROUND_TEMP","HGT_CLASS","HPREV","HTRY","HYDRO_NEXT","HYDRO_PREV","IGNITION_RATE","ISOILFLG","LATITUDE","LOAD_ADJACENCY","LONGITUDE","LSL","MINERALIZED_SOIL_N","MINERAL_SOIL_N_PY","MIN_MONTHLY_TEMP","MOIST_F","MOIST_TAU","MOIST_W","MOIST_ZI","NBIOMASS_UPTAKE","NBUDGET_INITIALSTORAGE","NCOHORTS_GLOBAL","NCOL_SOIL","NCWD_FLUX","NDCYCLE","NDEAD_GROW","NGROSS_MIN","NIRUP","NIR_B","NIR_B_BEAM","NIR_B_DIFFUSE","NLEAF_GROW","NLEAF_LITTER_FLUX","NLEV_SFCWATER","NMIN_INPUT","NMIN_LOSS","NNET_MIN","NPATCHES_GLOBAL","NPOLYGONS_GLOBAL","NROOT_GROW","NROOT_LITTER_FLUX","NSITES_GLOBAL","NSTORE_GROW","NUM_LANDUSE_YEARS","NZG","NZS","OPENCAN_FRAC","PACO_ID","PACO_N","PARUP","PAR_B","PAR_B_BEAM","PAR_B_DIFFUSE","PAR_G","PAR_G_BEAM","PAR_G_DIFFUSE","PAR_L_BEAM_MAX","PAR_L_DIFFUSE_MAX","PAR_L_MAX","PATCH_AREA","PATCH_COUNT","PLANTATION_SI","PLANTATION_STOCKING_DENSITY","PLANTATION_STOCKING_PFT","PLANT_AG_BIOMASS","PPTWEIGHT","PRIMARY_HARVEST_MEMORY","PRIMARY_HARVEST_TARGET","PYSI_ID","PYSI_N","QPWP","QRUNOFF","QSTAR","RAD_AVG","RH","RIBULK","RLONGUP","RLONG_ALBEDO","RLONG_G","RLONG_S","RNET","ROUGH","RSHORTUP","RSHORT_G","RSHORT_G_BEAM","RSHORT_G_DIFFUSE","RUNOFF","SECONDARY_HARVEST_MEMORY","SECONDARY_HARVEST_TARGET","SHEAT","SIPA_ID","SIPA_N","SITENUM","SLOPE","SLOW_SOIL_C","SLOW_SOIL_C_PY","SLXCLAY","SLXSAND","SLZ","SNOWFAC","SSC_IN","SSL_IN","STRUCTURAL_SOIL_C","STRUCTURAL_SOIL_L","STRUCT_SOIL_C_PY","STRUCT_SOIL_L_PY","SUM_CHD","SUM_DGD","SWLIQ","TCI","TE","TODAY_AF_DECOMP","TODAY_A_DECOMP","TOTAL_AGB","TOTAL_AGB_GROWTH","TOTAL_AGB_MORT","TOTAL_AGB_RECRUIT","TOTAL_BASAL_AREA","TOTAL_BASAL_AREA_GROWTH","TOTAL_BASAL_AREA_MORT","TOTAL_BASAL_AREA_RECRUIT","TOTAL_PLANT_NITROGEN_UPTAKE","TOTAL_SFCW_DEPTH","TPWP","TSTAR","UPWP","USTAR","VEG_DISPLACE","VEG_HEIGHT","VEG_ROUGH","WBAR","WBUDGET_DENSEFFECT","WBUDGET_INITIALSTORAGE","WBUDGET_LOSS2ATM","WBUDGET_LOSS2DRAINAGE","WBUDGET_LOSS2RUNOFF","WBUDGET_PRECIPGAIN","WBUDGET_RESIDUAL","WPWP","XATM","YATM","ZBAR","ZETA")
variables4 <- c("AGB_CUT","AGB_GROWTH","AGB_MORT","AGB_PY","AGB_SI","BALIVE_N_PY","BALIVE_PY","BASAL_AREA_CUT","BASAL_AREA_GROWTH","BASAL_AREA_MORT","BASAL_AREA_PY","BASAL_AREA_SI","BDEAD_N_PY","BDEAD_PY","BLEAF_N_PY","BLEAF_PY","BROOT_N_PY","BROOT_PY","BSAPWOODA_N_PY","BSAPWOODA_PY","BSAPWOODB_N_PY","BSAPWOODB_PY","BSEEDS_N_PY","BSEEDS_PY","BSTORAGE_N_PY","BSTORAGE_PY","CUMLAI_PROFILE","DISTURBANCE_MEMORY","DISTURBANCE_RATES","LAI_PY","LEAF_DROP_PY","LEAF_MAINTENANCE_PY","NPLANT_PY","ROOT_MAINTENANCE_PY","WAI_PY")
variables5 <- c("A_C_MAX","A_O_MAX","FMEAN_TRANSP_PFT","PAR_S","PAR_S_BEAM","PAR_S_DIFFUSE","PATCH_ROOT_DENSITY","REPRO_PA","RSHORT_S","RSHORT_S_BEAM","RSHORT_S_DIFFUSE","SFCWATER_DEPTH","SFCWATER_ENERGY","SFCWATER_FRACLIQ","SFCWATER_MASS","SFCWATER_TEMPK","SOIL_ENERGY_PA","SOIL_FRACLIQ_PA","SOIL_MSTPOT_PA","SOIL_TEMPK_PA","SOIL_WATER_PA")
variables6 <- c("WORKLOAD","GREEN_LEAF_FACTOR","LEAF_AGING_FACTOR","NTEXT_SOIL","LAMBDA_FIRE","AVG_MONTHLY_PCPG")

a <- list()
for (i in seq(length(variables))){
  var <- readDataSet(hfile[[variables[i]]])
  var_mod <- var[which2keep]
  a[[variables[i]]] <- var_mod
}

for (i in seq(length(variables2))){
  var <- readDataSet(hfile[[variables2[i]]])
  var_mod <- var[,which2keep]
  a[[variables2[i]]] <- var_mod
}

for (i in seq(length(variables3))){
  a[[variables3[i]]] <- readDataSet(hfile[[variables3[i]]])
}

for (i in seq(length(variables4))){
  temp <- readDataSet(hfile[[variables4[i]]])
  if (length(dim(temp)) == 2){
    a[[variables4[i]]] <- array(temp,c(dim(temp),1))
  } else {
    a[[variables4[i]]] <- temp
  }    
}

for (i in seq(length(variables5))){
  temp <- readDataSet(hfile[[variables5[i]]])
  if (is.null(dim(temp))){
    a[[variables5[i]]] <- array(temp,c(1,length(temp)))
  } else {
    a[[variables5[i]]] <- temp
  }    
}

for (i in seq(length(variables6))){
  temp <- readDataSet(hfile[[variables6[i]]])
  if (is.null(dim(temp))){
    a[[variables6[i]]] <- array(temp,c(length(temp),1))
  } else {
    a[[variables6[i]]] <- temp
  }    
}

a[["NCOHORTS_GLOBAL"]] <- as.integer(Ncohort)
a[["PACO_N"]] <- PAN_count
a[["PACO_ID"]] <- cumsum(c(1,PAN_count))[1:Npatch]

hfile$close_all()

if (file.exists(file_mod)) system(paste("rm",file_mod))
file.h5 <- H5File$new(file_mod, mode="w")

for (i in seq(1,length(a))){
  
  file.h5[[names(a[i])]] <- a[[i]]
}

file.h5$close_all()

}
